library verilog;
use verilog.vl_types.all;
entity coeff_selection is
    port(
        adc_section     : in     vl_logic_vector(1 downto 0);
        select_section_coefficients_coeff_4_9_porty: in     vl_logic_vector(31 downto 0);
        select_section_coefficients_coeff_4_8_porty: in     vl_logic_vector(31 downto 0);
        select_section_coefficients_coeff_4_7_porty: in     vl_logic_vector(31 downto 0);
        select_section_coefficients_coeff_4_6_porty: in     vl_logic_vector(31 downto 0);
        select_section_coefficients_coeff_4_5_porty: in     vl_logic_vector(31 downto 0);
        select_section_coefficients_coeff_4_4_porty: in     vl_logic_vector(31 downto 0);
        select_section_coefficients_coeff_4_3_porty: in     vl_logic_vector(31 downto 0);
        select_section_coefficients_coeff_4_2_porty: in     vl_logic_vector(31 downto 0);
        select_section_coefficients_coeff_4_10_porty: in     vl_logic_vector(31 downto 0);
        select_section_coefficients_coeff_4_1_porty: in     vl_logic_vector(31 downto 0);
        select_section_coefficients_coeff_4_0_porty: in     vl_logic_vector(31 downto 0);
        select_section_coefficients_coeff_3_9_porty: in     vl_logic_vector(31 downto 0);
        select_section_coefficients_coeff_3_8_porty: in     vl_logic_vector(31 downto 0);
        select_section_coefficients_coeff_3_7_porty: in     vl_logic_vector(31 downto 0);
        select_section_coefficients_coeff_3_6_porty: in     vl_logic_vector(31 downto 0);
        select_section_coefficients_coeff_3_5_porty: in     vl_logic_vector(31 downto 0);
        select_section_coefficients_coeff_3_4_porty: in     vl_logic_vector(31 downto 0);
        select_section_coefficients_coeff_3_3_porty: in     vl_logic_vector(31 downto 0);
        select_section_coefficients_coeff_3_2_porty: in     vl_logic_vector(31 downto 0);
        select_section_coefficients_coeff_3_10_porty: in     vl_logic_vector(31 downto 0);
        select_section_coefficients_coeff_3_1_porty: in     vl_logic_vector(31 downto 0);
        select_section_coefficients_coeff_3_0_porty: in     vl_logic_vector(31 downto 0);
        select_section_coefficients_coeff_2_9_porty: in     vl_logic_vector(31 downto 0);
        select_section_coefficients_coeff_2_8_porty: in     vl_logic_vector(31 downto 0);
        select_section_coefficients_coeff_2_7_porty: in     vl_logic_vector(31 downto 0);
        select_section_coefficients_coeff_2_6_porty: in     vl_logic_vector(31 downto 0);
        select_section_coefficients_coeff_2_5_porty: in     vl_logic_vector(31 downto 0);
        select_section_coefficients_coeff_2_4_porty: in     vl_logic_vector(31 downto 0);
        select_section_coefficients_coeff_2_3_porty: in     vl_logic_vector(31 downto 0);
        select_section_coefficients_coeff_2_2_porty: in     vl_logic_vector(31 downto 0);
        select_section_coefficients_coeff_2_10_porty: in     vl_logic_vector(31 downto 0);
        select_section_coefficients_coeff_2_1_porty: in     vl_logic_vector(31 downto 0);
        select_section_coefficients_coeff_2_0_porty: in     vl_logic_vector(31 downto 0);
        select_section_coefficients_coeff_1_9_porty: in     vl_logic_vector(31 downto 0);
        select_section_coefficients_coeff_1_8_porty: in     vl_logic_vector(31 downto 0);
        select_section_coefficients_coeff_1_7_porty: in     vl_logic_vector(31 downto 0);
        select_section_coefficients_coeff_1_6_porty: in     vl_logic_vector(31 downto 0);
        select_section_coefficients_coeff_1_5_porty: in     vl_logic_vector(31 downto 0);
        select_section_coefficients_coeff_1_4_porty: in     vl_logic_vector(31 downto 0);
        select_section_coefficients_coeff_1_3_porty: in     vl_logic_vector(31 downto 0);
        select_section_coefficients_coeff_1_2_porty: in     vl_logic_vector(31 downto 0);
        select_section_coefficients_coeff_1_10_porty: in     vl_logic_vector(31 downto 0);
        select_section_coefficients_coeff_1_1_porty: in     vl_logic_vector(31 downto 0);
        select_section_coefficients_coeff_1_0_porty: in     vl_logic_vector(31 downto 0);
        coeff1_o        : out    vl_logic_vector(31 downto 0);
        coeff2_o        : out    vl_logic_vector(31 downto 0);
        coeff3_o        : out    vl_logic_vector(31 downto 0);
        coeff4_o        : out    vl_logic_vector(31 downto 0);
        coeff5_o        : out    vl_logic_vector(31 downto 0);
        coeff6_o        : out    vl_logic_vector(31 downto 0);
        coeff7_o        : out    vl_logic_vector(31 downto 0);
        coeff8_o        : out    vl_logic_vector(31 downto 0);
        coeff9_o        : out    vl_logic_vector(31 downto 0);
        coeff10_o       : out    vl_logic_vector(31 downto 0);
        coeff0_o        : out    vl_logic_vector(31 downto 0)
    );
end coeff_selection;
